#ifndef COMMANDS_H
#define COMMANDS_H

#define BASE_SENSOR_DATA_LEN 9
#define ADCS_SENSOR_DATA_RESPONSE_SIZE 12
#define SAT_SENSOR_DATA_RESPONSE_SIZE 21

typedef enum {
    CMD_NONE = 0x00,
    CMD_SET_ADCS_MODE = 0x01,
    CMD_SET_ADCS_TARGET = 0x02,
    CMD_GET_BASE_SENSOR_DATA = 0x03,
    CMD_GET_SAT_TELEMETRY_DATA = 0x04,
    CMD_RESP_SAT_TELEMETRY_DATA = 0x15,
    CMD_RESP_BASE_SENSOR_DATA = 0x11,
    CMD_RESP_ACK = 0x20,
    CMD_RESP_NACK = 0x21
} CMD_e;

#endif